name: Sync from Org Repo

on:
#  schedule:
#    - cron: '*/10 * * * *'   # sync ทุก 10 นาที
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout personal repo (main)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}       # ใช้ PAT สำหรับ push ได้
          # fetch-depth: 0                  # ต้องดึง history เต็ม

      - name: Pull from Org repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # 1) ดึง upstream repo (repo ต้นทาง)
          git remote add upstream https://github.com/ramasrimed/roomdisplay.git
          git fetch upstream

          # 2) ดึง branch workflow จาก repo ปลายทาง
          git fetch origin workflow:workflow

          # 3) ไปที่ branch main ของ repo ปลายทาง
          git checkout main

          # 4) Mirror main ให้เหมือน upstream/main 100%
          git reset --hard upstream/main

          # 5) Restore workflow folder จาก branch workflow
          git checkout workflow -- .github/workflows

          # 6) Push กลับแบบ force เพื่อ sync ให้ตรง
          git add .
          git commit --amend --no-edit || true
          git push --force
