name: Sync from Org Repo

on:
#  schedule:
#    - cron: '*/10 * * * *'   # sync ทุก 10 นาที
  workflow_dispatch:
  push:
    branches:
      - main
      - workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout personal repo (main)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}       # ใช้ PAT สำหรับ push ได้
          fetch-depth: 0                  # ต้องดึง history เต็ม

      - name: Pull from Org repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # upstream
          git remote add upstream https://github.com/ramasrimed/roomdisplay.git
          git fetch upstream
          
          # local workflow branch
          git fetch origin workflow
          git branch workflow origin/workflow   # <<< สำคัญที่สุด
          
          # mirror main
          git checkout main
          git reset --hard upstream/main
          
          # restore workflows from workflow branch
          git checkout workflow -- .github/workflows
          
          # push back
          git add .
          git commit --amend --no-edit || true
          git push --force
