name: Sync from Org Repo

on:
#  schedule:
#    - cron: '*/10 * * * *'   # sync ทุก 10 นาที
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Debug PAT
        run: |
          echo "PAT length = ${#PAT}"
          echo "PAT length = ${{ secrets.PAT }}"

      - name: Checkout personal repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Pull from Org repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add upstream "https://github.com/ramasrimed/roomdisplay.git"
          git fetch upstream
          
          # เหมือนต้นฉบับ commit comment, message, history
          # แต่จะเอา workflows เก็บไว้
          git reset --hard upstream/main
          git restore --source=HEAD@{1} .github/workflows
          git push --force

          # เอาเฉพาะที่เพิ่ม/อัพเดทเท่านั้น กรณีต้นทางลบไฟล์จะไม่หายด้วย
        #  git merge upstream/main --no-edit || true
        #  git push
